### ISSUE TITLE
ROADMAP of Custom Pipeline

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/Custom-Pipeline#1]
- [ ] Add Mixture(Canvas) Pipeline
- [ ] Add Mixture(Tiling) Pipeline
- [ ] Add Stable Diffusionv1.5(Text2Image) Pipeline
- [ ] Add Stable Diffusionv1.5(Image2Image) Pipeline
- [ ] Add Stable Diffusionv1.5(Inpaint) Pipeline
